/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.dbInit.DbInitializer
import org.jetbrains.exposed.v1.jdbc.Database

fun main() {
    try {
        val dbConnection = Database.connect(
            url = System.getenv("dbURL"),
            user = System.getenv("dbUser"),
            password = System.getenv("dbPassword")
        )
        DbInitializer(dbConnection)
    } catch (e: Exception){
        println(e)
    }

}
