/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.ktor.http.HttpStatusCode
import io.ktor.server.application.install
import org.example.dbHandler.Handler

import io.ktor.server.netty.*
import io.ktor.server.routing.*
import io.ktor.server.engine.*
import io.ktor.server.response.*
import io.ktor.server.html.respondHtml
import io.ktor.server.htmx.hx
import io.ktor.server.http.content.staticResources
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.request.path
import io.ktor.server.request.receiveParameters
import io.ktor.utils.io.ExperimentalKtorApi
import kotlinx.html.*
import org.example.dataClasses.AccessibilityInformation
import org.example.dataClasses.Categories


import org.example.dataClasses.Contact
import org.example.dataClasses.Organization
import org.example.htmx.pages.allOrganizationsPage
import org.example.htmx.pages.updateOrganizationPage
import org.example.model.AccessibilityInformationTable
import org.example.model.CategoriesTable

import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.transactions.transaction

import org.example.model.ContactTable
import org.example.model.OrganizationTable
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.core.leftJoin
import java.time.format.DateTimeFormatter
import java.time.LocalDateTime

@OptIn(ExperimentalKtorApi::class)
fun main() {
    // Init the database so the model objects can be used
    Handler(false)
    val baseurl = "http://localhost:8081"

    embeddedServer(Netty, 8081) {

        install(StatusPages) {
            exception<Throwable> { call, cause ->
                call.application.environment.log.error("Request failed", cause)
                call.respondText("Something went wrong\n$cause")
            }
        }


        routing {
            staticResources("/static", "static")

            get("/all") {
                val contacts = mutableListOf<Map<String, String?>>()
                val organizations = mutableListOf<Map<String, String?>>()
                val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")

                transaction {
                    ContactTable.selectAll().forEach {
                        contacts.add(
                            mapOf(
                                "id" to it[ContactTable.id].toString(),
                                "organizationID" to it[ContactTable.organizationID].toString(),
                                "name" to it[ContactTable.name],
                                "pronouns" to it[ContactTable.pronouns],
                                "position" to it[ContactTable.position],
                                "directEmail" to it[ContactTable.directEmail],
                                "directPhone" to it[ContactTable.directPhone]
                            )
                        )
                    }
                    OrganizationTable.selectAll().forEach {
                        val lastUpdate = it[OrganizationTable.lastUpdate]
                        val formattedLastUpdate = lastUpdate.format(formatter) ?: "N/A"  // Format the lastUpdate or default to "N/A"


                        organizations.add(
                            mapOf(
                                "id" to it[OrganizationTable.id].toString(),
                                "name" to it[OrganizationTable.name],
                                "email" to it[OrganizationTable.email],
                                "streetAddress" to it[OrganizationTable.streetAddress],
                                "description" to it[OrganizationTable.description],
                                "city" to it[OrganizationTable.city],
                                "phoneNumber" to it[OrganizationTable.phoneNumber],
                                "province" to it[OrganizationTable.province],
                                "socialMedia" to it[OrganizationTable.socialMedia],
                                "website" to it[OrganizationTable.website],
                                "queerOwned" to it[OrganizationTable.queerOwned].toString(),
                                "queerInclusive" to it[OrganizationTable.queerInclusive].toString(),
                                "accessibilityID" to it[OrganizationTable.accessibilityInformation].toString(),
                                "categoryID" to it[OrganizationTable.categoryInformation].toString(),
                                "lastUpdate" to formattedLastUpdate
                            )
                        )
                    }
                }
                call.respondHtml { allOrganizationsPage(organizations,
                    call.request.path()) }

                return@get
            }

            get("/update/{orgID}") {

                try {
                    val queryID = call.parameters["orgID"]?.toInt() ?: -1
                    val contactInfo: MutableList<Contact> = mutableListOf()
                    var organizationInfo: Organization? = null
                    var accessibilityInfo: AccessibilityInformation? = null
                    var categories: Categories? = null

                    if (queryID == -1){
                        call.respondText { "Invalid query ID" }
                        return@get
                    }

                    transaction {
                        organizationInfo = OrganizationTable
                            .selectAll()
                            .where { OrganizationTable.id eq queryID }
                            .map { Organization.fromRow(it) }
                            .firstOrNull()

                        ContactTable.selectAll()
                            .where { ContactTable.organizationID eq queryID }
                            .forEach { contact ->
                                try {
                                    val contactFromRow = Contact.fromRow(contact)
                                    contactInfo.add(contactFromRow)
                                } catch (e: Exception) {
                                    println("Error in Contact.fromRow: ${e.message}")
                                }
                            }

                        accessibilityInfo = AccessibilityInformationTable
                            .leftJoin(OrganizationTable,
                                { AccessibilityInformationTable.id },
                                { OrganizationTable.accessibilityInformation })
                            .selectAll()
                            .where{ OrganizationTable.id eq queryID }
                            .map{ AccessibilityInformation.fromRow(it) }
                            .firstOrNull()

                        categories = CategoriesTable
                            .leftJoin(OrganizationTable,
                                { CategoriesTable.id },
                                { OrganizationTable.categoryInformation })
                            .selectAll()
                            .where{ OrganizationTable.id eq queryID }
                            .map{ Categories.fromRow(it) }
                            .firstOrNull()
                    }
                        call.respondHtml {
                            updateOrganizationPage(
                                organizationInfo as Organization,
                                contacts = contactInfo,
                                path = call.request.path(),
                                accessInfo = accessibilityInfo as AccessibilityInformation,
                                categoriesInfo = categories as Categories
                            )
                        }
                } catch (e: Exception) {
                    println("Error: ${e.message}")
                    call.respondText { "An error occurred: ${e.message}" }
                }
            }
            hx.post("/update/{orgID}"){
                val params = call.receiveParameters()
                val id = call.parameters["orgID"]?.toInt() ?: -1
                val accessibilityID = params["accessibilityID"]?.toInt() ?: -1
                val categoriesID = params["categoriesID"]?.toInt() ?: -1
                println("Parameters: ${params["accessibilityID"]?.toInt() ?: -1}")


                if(id == -1){
                    call.respondHtml(HttpStatusCode.BadRequest){
                        body{
                            p{ +"Error, invalid orgID provided" }
                        }
                    }
                    return@post
                }
                if(accessibilityID == -1){
                    println("invalid accessID: ${accessibilityID}\nraw: ${call.parameters["accessibilityID"]}")
                    call.respondHtml(HttpStatusCode.BadRequest){
                        body{
                            p{ +"Error, invalid Accessibility Information ID received: ${accessibilityID}" }
                        }
                    }
                    return@post
                }

                if(categoriesID == -1){
                    call.respondHtml(HttpStatusCode.BadRequest){
                        body{
                            p{ +"Error, invalid Categories Information ID received " }
                        }
                    }
                    return@post
                }


                val organization = Organization.fromMap(mapOf(
                    "id" to id,
                    "name" to params["name"],
                    "description" to params["description"],
                    "streetAddress" to params["streetAddress"],
                    "city" to params["city"],
                    "province" to params["province"],
                    "phone" to params["phone"],
                    "email" to params["email"],
                    "website" to params["website"],
                    "socialMedia" to params["socialMedia"],
                    "queerOwned" to params["queerOwned"],
                    "queerInclusive" to params["queerInclusive"],
                    "otherNotes" to params["otherNotes"],
                    "lastUpdate" to LocalDateTime.now()
                ))
                val accessibilityInformation = AccessibilityInformation.fromMap(mapOf(
                        "id" to accessibilityID,
                        "automaticDoors" to params["automaticDoors"],
                        "entrance" to params["entrance"],
                        "parking" to params["parking"],
                        "genderNeutralBathroom" to params["genderNeutralBathroom"],
                        "accessibleBathroom" to params["accessibleBathroom"],
                        "lastUpdate" to LocalDateTime.now()
                    ))
                // val categoriesInformation = Categories.fromMap()
                call.respondHtml(HttpStatusCode.OK){
                    body{
                        div { +organization.toString() }
                        br()
                        div { +accessibilityInformation.toString() }
                    }
                }

                return@post
            }

            hx.get("/update/get-new-contact-form"){
                call.respondText { """
                        <fieldset class="update-form-contact">
                            <legend>New Contact</legend>
                            <label for="newName">Name:</label>
                            <input type="text" name="newName" id="newName">
                            <br/>
                            <label for="newPronouns">Pronouns:</label>
                            <input type="text" name="newPronouns" id="newPronouns">
                            <br/>
                            <label for="newPosition">Position:</label>
                            <input type="text" name="newPosition" id="newPosition">
                            <br/>
                            <label for="newEmail">Direct Email:</label>
                            <input type="text" name="newEmail" id="newEmail">
                            <br/>
                            <label for="newPhone">Direct Phone:</label>
                            <input type="text" name="newPhone" id="newPhone">                            
                        </fieldset>
                        <div id="contactFormContainer"></div>
                    """.trimIndent()
                }
                return@get
            }
        }
    }.start(wait = true)
}