/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.dbHandler.Handler

import io.ktor.server.netty.*
import io.ktor.server.routing.*
import io.ktor.server.thymeleaf.*
import org.thymeleaf.templateresolver.ClassLoaderTemplateResolver
import io.ktor.server.engine.*
import io.ktor.server.html.*
import io.ktor.server.response.*
import io.ktor.server.application.*
import io.ktor.http.content.*
import io.ktor.server.http.content.files
import io.ktor.server.http.content.static
import io.ktor.server.http.content.staticResources
import io.ktor.server.plugins.origin
import io.ktor.server.plugins.statuspages.StatusPages
import kotlinx.html.*


import org.example.dataClasses.Contact
import org.example.dataClasses.Organization

import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.transactions.transaction

import org.example.model.ContactTable
import org.example.model.OrganizationTable
import org.jetbrains.exposed.v1.core.eq

fun main() {
    // Init the database so the model objects can be used
    Handler(true)
    val baseurl = "http://localhost:8081"

    embeddedServer(Netty, 8081) {
        // in your Application.module()
        install(Thymeleaf) {
            setTemplateResolver(
                ClassLoaderTemplateResolver().apply {
                    prefix = "templates/"
                    suffix = ".html"
                    characterEncoding = "utf-8"
                }
            )
        }

        install(StatusPages) {
            exception<Throwable> { call, cause ->
                call.application.environment.log.error("Request failed", cause)
                call.respondText("Something went wrong\n$cause")
            }
        }

        routing {
            staticResources("/static", "static")
            get("/all") {
                val contacts = mutableListOf<Map<String, String?>>()
                val organizations = mutableListOf<Map<String, String?>>()
                transaction {
                    ContactTable.selectAll().forEach {
                        contacts.add(
                            mapOf(
                                "id" to it[ContactTable.id].toString(),
                                "organizationID" to it[ContactTable.organizationID].toString(),
                                "name" to it[ContactTable.name],
                                "pronouns" to it[ContactTable.pronouns],
                                "position" to it[ContactTable.position],
                                "directEmail" to it[ContactTable.directEmail],
                                "directPhone" to it[ContactTable.directPhone]
                            )
                        )
                    }
                    OrganizationTable.selectAll().forEach {
                        organizations.add(
                            mapOf(
                                "id" to it[OrganizationTable.id].toString(),
                                "name" to it[OrganizationTable.name],
                                "streetAddress" to it[OrganizationTable.streetAddress],
                                "description" to it[OrganizationTable.description],
                                "city" to it[OrganizationTable.city],
                                "phoneNumber" to it[OrganizationTable.phoneNumber],
                                "province" to it[OrganizationTable.province],
                                "socialMedia" to it[OrganizationTable.socialMedia],
                                "website" to it[OrganizationTable.website],
                                "queerOwned" to it[OrganizationTable.queerOwned].toString(),
                                "queerInclusive" to it[OrganizationTable.queerInclusive].toString(),
                                "accessibilityID" to it[OrganizationTable.accessibilityInformation].toString(),
                                "categoryID" to it[OrganizationTable.categoryInformation].toString()
                            )
                        )
                    }
                }
                call.respond(ThymeleafContent("allOrganizations",
                    mapOf(
                        "organizations" to organizations,
                        "baseurl" to baseurl
                    )))
            }

            get("/update/{orgID}"){
                val queryID = call.parameters["orgID"]?.toInt() ?: -1
                val contactInfo: MutableList<Contact> = mutableListOf()
                var organizationInfo: Organization? = null

                transaction {
                    organizationInfo = OrganizationTable.selectAll()
                        .where { OrganizationTable.id eq queryID }
                        .map { Organization.fromRow(it) }
                        .firstOrNull()
                    ContactTable.selectAll()
                        .where{ ContactTable.organizationID eq queryID }
                        .map { Contact.fromRow(it) }
                        .forEach { contact -> contactInfo.add(contact) }
                }

                call.respondText{organizationInfo.toString() + "\n\n" + contactInfo.toString()}
            }
        }
    }.start(wait = true)
}